-- Health probe history generated by HealthChecker.

begin;

create table if not exists public.backend_health_checks (
    id bigint generated always as identity primary key,

    backend_id text not null
        references public.backend_services(id)
        on update cascade
        on delete restrict,

    checked_at timestamptz not null default now(),

    success boolean not null,
    status_code integer null,
    latency_ms numeric(14, 3) not null,

    error_type text null,
    error_message text null,

    consecutive_successes integer not null default 0,
    consecutive_failures integer not null default 0,

    resulting_status text not null,

    metadata jsonb not null default '{}'::jsonb,

    constraint backend_health_checks_status_code
        check (
            status_code is null
            or status_code between 100 and 599
        ),

    constraint backend_health_checks_nonnegative
        check (
            latency_ms >= 0
            and consecutive_successes >= 0
            and consecutive_failures >= 0
        ),

    constraint backend_health_checks_resulting_status
        check (resulting_status in (
            'unknown',
            'healthy',
            'unhealthy',
            'draining',
            'disabled'
        ))
);

create index if not exists idx_backend_health_checks_backend_time
    on public.backend_health_checks (backend_id, checked_at desc);

create index if not exists idx_backend_health_checks_failed_time
    on public.backend_health_checks (checked_at desc)
    where success = false;

commit;
