-- LoadFlow complete Supabase schema.
-- Generated by concatenating the numbered migration files.

-- =====================================================================
-- FILE: 00_extensions.sql
-- =====================================================================

-- LoadFlow database foundation.
-- Run first.

begin;

create extension if not exists pgcrypto;

commit;

-- =====================================================================
-- FILE: 01_backends.sql
-- =====================================================================

-- Backend configuration, current runtime state, and state-transition history.

begin;

create table if not exists public.backend_services (
    id text primary key,
    name text not null,
    url text not null,
    weight integer not null default 1,
    enabled boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz null,

    constraint backend_services_id_format
        check (id ~ '^[A-Za-z0-9][A-Za-z0-9_-]{1,63}$'),

    constraint backend_services_name_length
        check (char_length(name) between 2 and 100),

    constraint backend_services_url_length
        check (char_length(url) between 7 and 2048),

    constraint backend_services_weight_range
        check (weight between 1 and 100)
);

comment on table public.backend_services is
    'Durable backend definitions managed by the LoadFlow control API.';

create unique index if not exists uq_backend_services_active_url
    on public.backend_services (url)
    where deleted_at is null;

create index if not exists idx_backend_services_enabled
    on public.backend_services (enabled)
    where deleted_at is null;


create table if not exists public.backend_runtime_state (
    backend_id text primary key
        references public.backend_services(id)
        on update cascade
        on delete cascade,

    status text not null default 'unknown',
    active_requests integer not null default 0,
    total_requests bigint not null default 0,
    total_errors bigint not null default 0,

    last_latency_ms numeric(14, 3) null,
    last_checked_at timestamptz null,
    last_error text null,

    consecutive_successes integer not null default 0,
    consecutive_failures integer not null default 0,

    updated_at timestamptz not null default now(),

    constraint backend_runtime_state_status
        check (status in (
            'unknown',
            'healthy',
            'unhealthy',
            'draining',
            'disabled'
        )),

    constraint backend_runtime_state_nonnegative
        check (
            active_requests >= 0
            and total_requests >= 0
            and total_errors >= 0
            and consecutive_successes >= 0
            and consecutive_failures >= 0
            and (last_latency_ms is null or last_latency_ms >= 0)
        ),

    constraint backend_runtime_state_errors_not_above_total
        check (total_errors <= total_requests)
);

comment on table public.backend_runtime_state is
    'Current mutable health and request counters for each backend.';


create table if not exists public.backend_state_events (
    id uuid primary key default gen_random_uuid(),

    backend_id text not null
        references public.backend_services(id)
        on update cascade
        on delete restrict,

    from_status text null,
    to_status text not null,

    event_type text not null default 'status_changed',
    reason text null,
    source text not null default 'system',
    metadata jsonb not null default '{}'::jsonb,

    occurred_at timestamptz not null default now(),
    created_at timestamptz not null default now(),

    constraint backend_state_events_from_status
        check (
            from_status is null
            or from_status in (
                'unknown',
                'healthy',
                'unhealthy',
                'draining',
                'disabled'
            )
        ),

    constraint backend_state_events_to_status
        check (to_status in (
            'unknown',
            'healthy',
            'unhealthy',
            'draining',
            'disabled'
        ))
);

create index if not exists idx_backend_state_events_backend_time
    on public.backend_state_events (backend_id, occurred_at desc);

create index if not exists idx_backend_state_events_type_time
    on public.backend_state_events (event_type, occurred_at desc);

commit;

-- =====================================================================
-- FILE: 02_routing_and_settings.sql
-- =====================================================================

-- Active routing configuration, configuration history, and platform settings.

begin;

create table if not exists public.routing_configuration (
    singleton_id smallint primary key default 1,
    algorithm text not null default 'round_robin',
    config jsonb not null default '{}'::jsonb,
    updated_by text null,
    updated_at timestamptz not null default now(),

    constraint routing_configuration_singleton
        check (singleton_id = 1),

    constraint routing_configuration_algorithm
        check (algorithm in (
            'round_robin',
            'smooth_weighted_round_robin',
            'least_inflight'
        ))
);

create table if not exists public.routing_configuration_history (
    id uuid primary key default gen_random_uuid(),

    previous_algorithm text null,
    algorithm text not null,

    previous_config jsonb null,
    config jsonb not null default '{}'::jsonb,

    changed_by text null,
    reason text null,
    changed_at timestamptz not null default now(),

    constraint routing_configuration_history_previous_algorithm
        check (
            previous_algorithm is null
            or previous_algorithm in (
                'round_robin',
                'smooth_weighted_round_robin',
                'least_inflight'
            )
        ),

    constraint routing_configuration_history_algorithm
        check (algorithm in (
            'round_robin',
            'smooth_weighted_round_robin',
            'least_inflight'
        ))
);

create index if not exists idx_routing_configuration_history_changed_at
    on public.routing_configuration_history (changed_at desc);


create table if not exists public.platform_settings (
    singleton_id smallint primary key default 1,

    request_timeout_seconds numeric(10, 3) not null default 15,
    connect_timeout_seconds numeric(10, 3) not null default 3,

    health_check_enabled boolean not null default true,
    health_check_interval_seconds numeric(10, 3) not null default 5,
    healthy_threshold integer not null default 2,
    unhealthy_threshold integer not null default 3,

    max_request_body_bytes bigint not null default 10485760,

    rate_limit_requests integer not null default 300,
    rate_limit_window_seconds integer not null default 60,

    expose_selected_backend_header boolean not null default false,

    metadata jsonb not null default '{}'::jsonb,
    updated_by text null,
    updated_at timestamptz not null default now(),

    constraint platform_settings_singleton
        check (singleton_id = 1),

    constraint platform_settings_positive_values
        check (
            request_timeout_seconds > 0
            and connect_timeout_seconds > 0
            and health_check_interval_seconds > 0
            and healthy_threshold >= 1
            and unhealthy_threshold >= 1
            and max_request_body_bytes >= 1
            and rate_limit_requests >= 1
            and rate_limit_window_seconds >= 1
        )
);

commit;

-- =====================================================================
-- FILE: 03_load_testing.sql
-- =====================================================================

-- Load-test run history, interval samples, and per-backend aggregate results.

begin;

create table if not exists public.load_test_runs (
    id uuid primary key default gen_random_uuid(),
    external_id text not null unique,

    name text null,
    target_path text not null default '/api/demo',

    status text not null default 'pending',
    duration_seconds integer not null,
    concurrency integer not null,

    selected_algorithm text null,

    started_at timestamptz null,
    completed_at timestamptz null,

    progress integer not null default 0,

    throughput_rps numeric(14, 3) not null default 0,
    average_latency_ms numeric(14, 3) not null default 0,
    p50_latency_ms numeric(14, 3) not null default 0,
    p95_latency_ms numeric(14, 3) not null default 0,
    p99_latency_ms numeric(14, 3) not null default 0,

    error_rate numeric(7, 4) not null default 0,

    success_count bigint not null default 0,
    error_count bigint not null default 0,
    total_requests bigint generated always as (success_count + error_count) stored,

    parameters jsonb not null default '{}'::jsonb,
    result_metadata jsonb not null default '{}'::jsonb,

    created_by text null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint load_test_runs_status
        check (status in (
            'pending',
            'running',
            'completed',
            'failed',
            'cancelled'
        )),

    constraint load_test_runs_algorithm
        check (
            selected_algorithm is null
            or selected_algorithm in (
                'round_robin',
                'smooth_weighted_round_robin',
                'least_inflight'
            )
        ),

    constraint load_test_runs_positive_configuration
        check (duration_seconds >= 1 and concurrency >= 1),

    constraint load_test_runs_progress_range
        check (progress between 0 and 100),

    constraint load_test_runs_metrics_nonnegative
        check (
            throughput_rps >= 0
            and average_latency_ms >= 0
            and p50_latency_ms >= 0
            and p95_latency_ms >= 0
            and p99_latency_ms >= 0
            and error_rate between 0 and 100
            and success_count >= 0
            and error_count >= 0
        ),

    constraint load_test_runs_time_order
        check (
            completed_at is null
            or started_at is null
            or completed_at >= started_at
        )
);

create index if not exists idx_load_test_runs_created_at
    on public.load_test_runs (created_at desc);

create index if not exists idx_load_test_runs_status_created_at
    on public.load_test_runs (status, created_at desc);


create table if not exists public.load_test_samples (
    id bigint generated always as identity primary key,

    load_test_run_id uuid not null
        references public.load_test_runs(id)
        on delete cascade,

    sampled_at timestamptz not null default now(),

    progress integer not null,
    throughput_rps numeric(14, 3) not null default 0,

    average_latency_ms numeric(14, 3) not null default 0,
    p50_latency_ms numeric(14, 3) not null default 0,
    p95_latency_ms numeric(14, 3) not null default 0,
    p99_latency_ms numeric(14, 3) not null default 0,

    success_count bigint not null default 0,
    error_count bigint not null default 0,
    error_rate numeric(7, 4) not null default 0,

    metadata jsonb not null default '{}'::jsonb,

    constraint load_test_samples_progress_range
        check (progress between 0 and 100),

    constraint load_test_samples_nonnegative
        check (
            throughput_rps >= 0
            and average_latency_ms >= 0
            and p50_latency_ms >= 0
            and p95_latency_ms >= 0
            and p99_latency_ms >= 0
            and success_count >= 0
            and error_count >= 0
            and error_rate between 0 and 100
        )
);

create index if not exists idx_load_test_samples_run_time
    on public.load_test_samples (load_test_run_id, sampled_at);


create table if not exists public.load_test_backend_results (
    load_test_run_id uuid not null
        references public.load_test_runs(id)
        on delete cascade,

    backend_id text not null
        references public.backend_services(id)
        on update cascade
        on delete restrict,

    request_count bigint not null default 0,
    success_count bigint not null default 0,
    error_count bigint not null default 0,

    average_latency_ms numeric(14, 3) not null default 0,
    p95_latency_ms numeric(14, 3) not null default 0,
    p99_latency_ms numeric(14, 3) not null default 0,

    metadata jsonb not null default '{}'::jsonb,

    primary key (load_test_run_id, backend_id),

    constraint load_test_backend_results_nonnegative
        check (
            request_count >= 0
            and success_count >= 0
            and error_count >= 0
            and success_count + error_count <= request_count
            and average_latency_ms >= 0
            and p95_latency_ms >= 0
            and p99_latency_ms >= 0
        )
);

commit;

-- =====================================================================
-- FILE: 04_api_ingest_worker.sql
-- =====================================================================

-- Durable queue used by a background worker to persist completed API events.

begin;

create table if not exists public.api_ingest_jobs (
    id uuid primary key default gen_random_uuid(),

    request_id text not null unique,
    correlation_id text null,

    http_method text not null,
    route text not null,
    query_present boolean not null default false,
    received_at timestamptz not null default now(),

    status text not null default 'pending',
    priority smallint not null default 100,

    attempt_count integer not null default 0,
    max_attempts integer not null default 5,

    available_at timestamptz not null default now(),

    locked_at timestamptz null,
    locked_by text null,
    processing_started_at timestamptz null,
    completed_at timestamptz null,

    last_error_type text null,
    last_error_code text null,
    last_error_message text null,

    payload jsonb not null default '{}'::jsonb,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint api_ingest_jobs_status
        check (status in (
            'pending',
            'processing',
            'retry',
            'completed',
            'failed',
            'discarded'
        )),

    constraint api_ingest_jobs_priority_range
        check (priority between 0 and 1000),

    constraint api_ingest_jobs_attempts
        check (
            attempt_count >= 0
            and max_attempts >= 1
            and attempt_count <= max_attempts
        ),

    constraint api_ingest_jobs_lock_consistency
        check (
            (
                status = 'processing'
                and locked_at is not null
                and locked_by is not null
            )
            or status <> 'processing'
        ),

    constraint api_ingest_jobs_completed_time
        check (
            completed_at is null
            or completed_at >= received_at
        )
);

comment on column public.api_ingest_jobs.payload is
    'Sanitized completed-request payload. Never store credentials, cookies, tokens, or raw bodies.';

create index if not exists idx_api_ingest_jobs_claim
    on public.api_ingest_jobs (
        status,
        available_at,
        priority,
        received_at
    )
    where status in ('pending', 'retry');

create index if not exists idx_api_ingest_jobs_locked_at
    on public.api_ingest_jobs (locked_at)
    where status = 'processing';

create index if not exists idx_api_ingest_jobs_received_at
    on public.api_ingest_jobs (received_at desc);

create index if not exists idx_api_ingest_jobs_correlation_id
    on public.api_ingest_jobs (correlation_id)
    where correlation_id is not null;

commit;

-- =====================================================================
-- FILE: 05_api_request_history.sql
-- =====================================================================

-- One row for each logical request completed by the load balancer.

begin;

create table if not exists public.api_request_history (
    id uuid primary key default gen_random_uuid(),

    request_id text not null unique,
    correlation_id text null,

    received_at timestamptz not null,
    completed_at timestamptz not null,

    http_method text not null,
    route text not null,
    query_present boolean not null default false,

    request_size_bytes bigint null,
    response_size_bytes bigint null,

    final_status_code integer not null,
    total_duration_ms numeric(14, 3) not null,

    selected_algorithm text not null,

    final_backend_id text null
        references public.backend_services(id)
        on update cascade
        on delete set null,

    attempt_count integer not null default 1,
    retry_count integer not null default 0,

    outcome text not null,

    error_type text null,
    error_code text null,
    error_message text null,

    worker_job_id uuid null
        references public.api_ingest_jobs(id)
        on delete set null,

    load_test_run_id uuid null
        references public.load_test_runs(id)
        on delete set null,

    client_ip inet null,
    client_ip_hash text null,
    user_agent_family text null,

    metadata jsonb not null default '{}'::jsonb,

    created_at timestamptz not null default now(),

    constraint api_request_history_method_length
        check (char_length(http_method) between 1 and 16),

    constraint api_request_history_status_code
        check (final_status_code between 100 and 599),

    constraint api_request_history_nonnegative
        check (
            total_duration_ms >= 0
            and attempt_count >= 0
            and retry_count >= 0
            and retry_count <= attempt_count
            and (request_size_bytes is null or request_size_bytes >= 0)
            and (response_size_bytes is null or response_size_bytes >= 0)
        ),

    constraint api_request_history_time_order
        check (completed_at >= received_at),

    constraint api_request_history_algorithm
        check (selected_algorithm in (
            'round_robin',
            'smooth_weighted_round_robin',
            'least_inflight',
            'none'
        )),

    constraint api_request_history_outcome
        check (outcome in (
            'success',
            'client_error',
            'upstream_error',
            'timeout',
            'rejected',
            'cancelled',
            'internal_error',
            'no_healthy_backend'
        ))
);

comment on table public.api_request_history is
    'Completed logical request history used by logs, analytics, and request tracking pages.';

comment on column public.api_request_history.metadata is
    'Sanitized optional context. Never store authorization headers, cookies, tokens, or full bodies.';

create index if not exists idx_api_request_history_received_at
    on public.api_request_history (received_at desc);

create index if not exists idx_api_request_history_completed_at
    on public.api_request_history (completed_at desc);

create index if not exists idx_api_request_history_correlation_id
    on public.api_request_history (correlation_id)
    where correlation_id is not null;

create index if not exists idx_api_request_history_route_received_at
    on public.api_request_history (route, received_at desc);

create index if not exists idx_api_request_history_status_received_at
    on public.api_request_history (final_status_code, received_at desc);

create index if not exists idx_api_request_history_backend_received_at
    on public.api_request_history (final_backend_id, received_at desc)
    where final_backend_id is not null;

create index if not exists idx_api_request_history_algorithm_received_at
    on public.api_request_history (selected_algorithm, received_at desc);

create index if not exists idx_api_request_history_outcome_received_at
    on public.api_request_history (outcome, received_at desc);

create index if not exists idx_api_request_history_load_test_run
    on public.api_request_history (load_test_run_id, received_at)
    where load_test_run_id is not null;

create index if not exists idx_api_request_history_metadata_gin
    on public.api_request_history using gin (metadata);

commit;

-- =====================================================================
-- FILE: 06_api_request_attempts.sql
-- =====================================================================

-- One row for every backend selection/attempt, including retry and failover.

begin;

create table if not exists public.api_request_attempts (
    id uuid primary key default gen_random_uuid(),

    api_request_id uuid not null
        references public.api_request_history(id)
        on delete cascade,

    request_id text not null,
    attempt_number integer not null,

    backend_id text null
        references public.backend_services(id)
        on update cascade
        on delete set null,

    selected_algorithm text not null,

    started_at timestamptz not null,
    completed_at timestamptz not null,

    duration_ms numeric(14, 3) not null,

    upstream_status_code integer null,

    outcome text not null,

    retryable boolean not null default false,
    retry_scheduled boolean not null default false,

    error_type text null,
    error_code text null,
    error_message text null,

    metadata jsonb not null default '{}'::jsonb,

    created_at timestamptz not null default now(),

    unique (api_request_id, attempt_number),
    unique (request_id, attempt_number),

    constraint api_request_attempts_number
        check (attempt_number >= 1),

    constraint api_request_attempts_duration
        check (duration_ms >= 0),

    constraint api_request_attempts_status
        check (
            upstream_status_code is null
            or upstream_status_code between 100 and 599
        ),

    constraint api_request_attempts_time_order
        check (completed_at >= started_at),

    constraint api_request_attempts_algorithm
        check (selected_algorithm in (
            'round_robin',
            'smooth_weighted_round_robin',
            'least_inflight',
            'none'
        )),

    constraint api_request_attempts_outcome
        check (outcome in (
            'success',
            'upstream_error',
            'connect_error',
            'connect_timeout',
            'read_timeout',
            'stream_error',
            'request_body_too_large',
            'cancelled',
            'internal_error',
            'no_healthy_backend'
        ))
);

create index if not exists idx_api_request_attempts_request
    on public.api_request_attempts (api_request_id, attempt_number);

create index if not exists idx_api_request_attempts_backend_time
    on public.api_request_attempts (backend_id, started_at desc)
    where backend_id is not null;

create index if not exists idx_api_request_attempts_outcome_time
    on public.api_request_attempts (outcome, started_at desc);

create index if not exists idx_api_request_attempts_error_code
    on public.api_request_attempts (error_code, started_at desc)
    where error_code is not null;

commit;

-- =====================================================================
-- FILE: 07_backend_health.sql
-- =====================================================================

-- Health probe history generated by HealthChecker.

begin;

create table if not exists public.backend_health_checks (
    id bigint generated always as identity primary key,

    backend_id text not null
        references public.backend_services(id)
        on update cascade
        on delete restrict,

    checked_at timestamptz not null default now(),

    success boolean not null,
    status_code integer null,
    latency_ms numeric(14, 3) not null,

    error_type text null,
    error_message text null,

    consecutive_successes integer not null default 0,
    consecutive_failures integer not null default 0,

    resulting_status text not null,

    metadata jsonb not null default '{}'::jsonb,

    constraint backend_health_checks_status_code
        check (
            status_code is null
            or status_code between 100 and 599
        ),

    constraint backend_health_checks_nonnegative
        check (
            latency_ms >= 0
            and consecutive_successes >= 0
            and consecutive_failures >= 0
        ),

    constraint backend_health_checks_resulting_status
        check (resulting_status in (
            'unknown',
            'healthy',
            'unhealthy',
            'draining',
            'disabled'
        ))
);

create index if not exists idx_backend_health_checks_backend_time
    on public.backend_health_checks (backend_id, checked_at desc);

create index if not exists idx_backend_health_checks_failed_time
    on public.backend_health_checks (checked_at desc)
    where success = false;

commit;

-- =====================================================================
-- FILE: 08_security.sql
-- =====================================================================

-- Rate-limit, authentication, and suspicious-request history.

begin;

create table if not exists public.security_events (
    id uuid primary key default gen_random_uuid(),

    event_type text not null,
    severity text not null default 'warning',

    title text not null,

    client_ip inet null,
    client_ip_hash text null,

    request_id text null,
    correlation_id text null,

    route text null,
    http_method text null,

    blocked boolean not null default false,

    metadata jsonb not null default '{}'::jsonb,

    occurred_at timestamptz not null default now(),
    created_at timestamptz not null default now(),

    constraint security_events_type
        check (event_type in (
            'rate_limit_exceeded',
            'auth_failure',
            'suspicious_request',
            'sql_injection_detected',
            'suspicious_user_agent',
            'ip_blocked',
            'ip_unblocked',
            'other'
        )),

    constraint security_events_severity
        check (severity in (
            'info',
            'warning',
            'error',
            'critical'
        ))
);

create index if not exists idx_security_events_time
    on public.security_events (occurred_at desc);

create index if not exists idx_security_events_type_time
    on public.security_events (event_type, occurred_at desc);

create index if not exists idx_security_events_ip_time
    on public.security_events (client_ip, occurred_at desc)
    where client_ip is not null;

create index if not exists idx_security_events_request_id
    on public.security_events (request_id)
    where request_id is not null;


create table if not exists public.security_ip_counters (
    client_ip inet primary key,

    rate_limit_hits bigint not null default 0,
    auth_failures bigint not null default 0,
    suspicious_events bigint not null default 0,

    blocked_until timestamptz null,

    first_seen_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),

    metadata jsonb not null default '{}'::jsonb,

    constraint security_ip_counters_nonnegative
        check (
            rate_limit_hits >= 0
            and auth_failures >= 0
            and suspicious_events >= 0
        )
);

create index if not exists idx_security_ip_counters_last_seen
    on public.security_ip_counters (last_seen_at desc);

create index if not exists idx_security_ip_counters_total_events
    on public.security_ip_counters (
        (rate_limit_hits + auth_failures + suspicious_events) desc
    );

commit;

-- =====================================================================
-- FILE: 09_system_logs.sql
-- =====================================================================

-- Structured operational logs. Raw console/debug logs should remain in the
-- deployment logging platform.

begin;

create table if not exists public.system_logs (
    id uuid primary key default gen_random_uuid(),

    occurred_at timestamptz not null default now(),

    level text not null,
    event_name text not null,
    component text not null,
    message text not null,

    request_id text null,
    correlation_id text null,
    backend_id text null,

    http_method text null,
    route text null,
    status_code integer null,

    duration_ms numeric(14, 3) null,

    error_type text null,
    error_code text null,

    metadata jsonb not null default '{}'::jsonb,

    created_at timestamptz not null default now(),

    constraint system_logs_level
        check (level in (
            'debug',
            'info',
            'warning',
            'error',
            'critical'
        )),

    constraint system_logs_status_code
        check (
            status_code is null
            or status_code between 100 and 599
        ),

    constraint system_logs_duration
        check (duration_ms is null or duration_ms >= 0)
);

comment on column public.system_logs.metadata is
    'Sanitized context only. Do not store passwords, tokens, cookies, or raw bodies.';

create index if not exists idx_system_logs_occurred_at
    on public.system_logs (occurred_at desc);

create index if not exists idx_system_logs_level_time
    on public.system_logs (level, occurred_at desc);

create index if not exists idx_system_logs_event_time
    on public.system_logs (event_name, occurred_at desc);

create index if not exists idx_system_logs_component_time
    on public.system_logs (component, occurred_at desc);

create index if not exists idx_system_logs_request_id
    on public.system_logs (request_id)
    where request_id is not null;

create index if not exists idx_system_logs_backend_time
    on public.system_logs (backend_id, occurred_at desc)
    where backend_id is not null;

create index if not exists idx_system_logs_metadata_gin
    on public.system_logs using gin (metadata);

commit;

-- =====================================================================
-- FILE: 10_audit_and_alerts.sql
-- =====================================================================

-- Administrative audit history and per-actor alert acknowledgements.

begin;

create table if not exists public.audit_events (
    id uuid primary key default gen_random_uuid(),

    actor_id text null,
    actor_type text not null default 'admin_api_key',

    action text not null,
    object_type text not null,
    object_id text null,

    previous_state jsonb null,
    new_state jsonb null,

    reason text null,

    request_id text null,
    correlation_id text null,

    client_ip inet null,

    occurred_at timestamptz not null default now(),
    created_at timestamptz not null default now(),

    metadata jsonb not null default '{}'::jsonb,

    constraint audit_events_actor_type
        check (actor_type in (
            'admin_api_key',
            'user',
            'system',
            'worker'
        ))
);

create index if not exists idx_audit_events_time
    on public.audit_events (occurred_at desc);

create index if not exists idx_audit_events_object
    on public.audit_events (object_type, object_id, occurred_at desc);

create index if not exists idx_audit_events_actor
    on public.audit_events (actor_id, occurred_at desc)
    where actor_id is not null;


create table if not exists public.alert_acknowledgements (
    alert_key text not null,
    actor_id text not null default 'default-admin',

    acknowledged_at timestamptz not null default now(),
    note text null,

    primary key (alert_key, actor_id)
);

create index if not exists idx_alert_acknowledgements_actor_time
    on public.alert_acknowledgements (actor_id, acknowledged_at desc);

commit;

-- =====================================================================
-- FILE: 11_db_pool_samples.sql
-- =====================================================================

-- Periodic application-side database connection-pool metrics.

begin;

create table if not exists public.db_pool_samples (
    id bigint generated always as identity primary key,

    instance_id text not null,
    sampled_at timestamptz not null default now(),

    configured_pool_size integer not null,
    checked_in_connections integer not null,
    checked_out_connections integer not null,
    overflow_connections integer not null,

    acquisition_wait_ms numeric(14, 3) null,
    timeout_count bigint not null default 0,
    connection_error_count bigint not null default 0,

    metadata jsonb not null default '{}'::jsonb,

    constraint db_pool_samples_nonnegative
        check (
            configured_pool_size >= 0
            and checked_in_connections >= 0
            and checked_out_connections >= 0
            and overflow_connections >= 0
            and (acquisition_wait_ms is null or acquisition_wait_ms >= 0)
            and timeout_count >= 0
            and connection_error_count >= 0
        )
);

create index if not exists idx_db_pool_samples_instance_time
    on public.db_pool_samples (instance_id, sampled_at desc);

create index if not exists idx_db_pool_samples_time
    on public.db_pool_samples (sampled_at desc);

commit;

-- =====================================================================
-- FILE: 12_triggers_and_storage_functions.sql
-- =====================================================================

-- Shared triggers and reusable write/worker functions.
-- Functions use the lf_ prefix so permissions can be managed safely.

begin;

-- ---------------------------------------------------------------------------
-- updated_at helper
-- ---------------------------------------------------------------------------

create or replace function public.lf_set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_backend_services_updated_at
    on public.backend_services;

create trigger trg_backend_services_updated_at
before update on public.backend_services
for each row
execute function public.lf_set_updated_at();

drop trigger if exists trg_backend_runtime_state_updated_at
    on public.backend_runtime_state;

create trigger trg_backend_runtime_state_updated_at
before update on public.backend_runtime_state
for each row
execute function public.lf_set_updated_at();

drop trigger if exists trg_platform_settings_updated_at
    on public.platform_settings;

create trigger trg_platform_settings_updated_at
before update on public.platform_settings
for each row
execute function public.lf_set_updated_at();

drop trigger if exists trg_load_test_runs_updated_at
    on public.load_test_runs;

create trigger trg_load_test_runs_updated_at
before update on public.load_test_runs
for each row
execute function public.lf_set_updated_at();

drop trigger if exists trg_api_ingest_jobs_updated_at
    on public.api_ingest_jobs;

create trigger trg_api_ingest_jobs_updated_at
before update on public.api_ingest_jobs
for each row
execute function public.lf_set_updated_at();


-- ---------------------------------------------------------------------------
-- Backend storage
-- ---------------------------------------------------------------------------

create or replace function public.lf_upsert_backend(
    p_id text,
    p_name text,
    p_url text,
    p_weight integer default 1,
    p_enabled boolean default true
)
returns public.backend_services
language plpgsql
as $$
declare
    v_backend public.backend_services;
begin
    insert into public.backend_services (
        id,
        name,
        url,
        weight,
        enabled,
        deleted_at
    )
    values (
        btrim(p_id),
        btrim(p_name),
        btrim(p_url),
        p_weight,
        p_enabled,
        null
    )
    on conflict (id) do update
    set
        name = excluded.name,
        url = excluded.url,
        weight = excluded.weight,
        enabled = excluded.enabled,
        deleted_at = null
    returning * into v_backend;

    insert into public.backend_runtime_state (
        backend_id,
        status
    )
    values (
        v_backend.id,
        case when v_backend.enabled then 'unknown' else 'disabled' end
    )
    on conflict (backend_id) do nothing;

    return v_backend;
end;
$$;


create or replace function public.lf_soft_delete_backend(
    p_backend_id text,
    p_actor_id text default null,
    p_reason text default null
)
returns boolean
language plpgsql
as $$
declare
    v_previous jsonb;
    v_updated integer;
begin
    select to_jsonb(b)
    into v_previous
    from public.backend_services b
    where b.id = p_backend_id
      and b.deleted_at is null;

    update public.backend_services
    set
        enabled = false,
        deleted_at = now()
    where id = p_backend_id
      and deleted_at is null;

    get diagnostics v_updated = row_count;

    if v_updated = 1 then
        update public.backend_runtime_state
        set status = 'disabled'
        where backend_id = p_backend_id;

        insert into public.audit_events (
            actor_id,
            action,
            object_type,
            object_id,
            previous_state,
            new_state,
            reason
        )
        values (
            p_actor_id,
            'backend_deleted',
            'backend',
            p_backend_id,
            v_previous,
            jsonb_build_object('deleted_at', now(), 'enabled', false),
            p_reason
        );
    end if;

    return v_updated = 1;
end;
$$;


create or replace function public.lf_set_backend_enabled(
    p_backend_id text,
    p_enabled boolean,
    p_actor_id text default null,
    p_reason text default null
)
returns public.backend_services
language plpgsql
as $$
declare
    v_backend public.backend_services;
    v_old_status text;
    v_new_status text;
begin
    select status
    into v_old_status
    from public.backend_runtime_state
    where backend_id = p_backend_id
    for update;

    update public.backend_services
    set enabled = p_enabled
    where id = p_backend_id
      and deleted_at is null
    returning * into v_backend;

    if not found then
        raise exception 'Backend not found: %', p_backend_id;
    end if;

    v_new_status := case when p_enabled then 'unknown' else 'disabled' end;

    update public.backend_runtime_state
    set status = v_new_status
    where backend_id = p_backend_id;

    if v_old_status is distinct from v_new_status then
        insert into public.backend_state_events (
            backend_id,
            from_status,
            to_status,
            event_type,
            reason,
            source
        )
        values (
            p_backend_id,
            v_old_status,
            v_new_status,
            case when p_enabled then 'enabled' else 'disabled' end,
            p_reason,
            coalesce(p_actor_id, 'system')
        );
    end if;

    insert into public.audit_events (
        actor_id,
        action,
        object_type,
        object_id,
        new_state,
        reason
    )
    values (
        p_actor_id,
        case when p_enabled then 'backend_enabled' else 'backend_disabled' end,
        'backend',
        p_backend_id,
        jsonb_build_object('enabled', p_enabled, 'status', v_new_status),
        p_reason
    );

    return v_backend;
end;
$$;


create or replace function public.lf_set_backend_draining(
    p_backend_id text,
    p_actor_id text default null,
    p_reason text default null
)
returns boolean
language plpgsql
as $$
declare
    v_old_status text;
begin
    select status
    into v_old_status
    from public.backend_runtime_state
    where backend_id = p_backend_id
    for update;

    if not found then
        raise exception 'Backend not found: %', p_backend_id;
    end if;

    update public.backend_runtime_state
    set status = 'draining'
    where backend_id = p_backend_id;

    insert into public.backend_state_events (
        backend_id,
        from_status,
        to_status,
        event_type,
        reason,
        source
    )
    values (
        p_backend_id,
        v_old_status,
        'draining',
        'draining_enabled',
        p_reason,
        coalesce(p_actor_id, 'system')
    );

    insert into public.audit_events (
        actor_id,
        action,
        object_type,
        object_id,
        new_state,
        reason
    )
    values (
        p_actor_id,
        'backend_draining',
        'backend',
        p_backend_id,
        '{"status":"draining"}'::jsonb,
        p_reason
    );

    return true;
end;
$$;


-- ---------------------------------------------------------------------------
-- Routing configuration
-- ---------------------------------------------------------------------------

create or replace function public.lf_set_routing_algorithm(
    p_algorithm text,
    p_config jsonb default '{}'::jsonb,
    p_changed_by text default null,
    p_reason text default null
)
returns public.routing_configuration
language plpgsql
as $$
declare
    v_previous public.routing_configuration;
    v_current public.routing_configuration;
begin
    if p_algorithm not in (
        'round_robin',
        'smooth_weighted_round_robin',
        'least_inflight'
    ) then
        raise exception 'Unsupported algorithm: %', p_algorithm;
    end if;

    select *
    into v_previous
    from public.routing_configuration
    where singleton_id = 1
    for update;

    insert into public.routing_configuration (
        singleton_id,
        algorithm,
        config,
        updated_by
    )
    values (
        1,
        p_algorithm,
        coalesce(p_config, '{}'::jsonb),
        p_changed_by
    )
    on conflict (singleton_id) do update
    set
        algorithm = excluded.algorithm,
        config = excluded.config,
        updated_by = excluded.updated_by,
        updated_at = now()
    returning * into v_current;

    insert into public.routing_configuration_history (
        previous_algorithm,
        algorithm,
        previous_config,
        config,
        changed_by,
        reason
    )
    values (
        v_previous.algorithm,
        v_current.algorithm,
        v_previous.config,
        v_current.config,
        p_changed_by,
        p_reason
    );

    insert into public.audit_events (
        actor_id,
        action,
        object_type,
        object_id,
        previous_state,
        new_state,
        reason
    )
    values (
        p_changed_by,
        'routing_algorithm_changed',
        'routing_configuration',
        '1',
        case
            when v_previous.algorithm is null then null
            else jsonb_build_object(
                'algorithm', v_previous.algorithm,
                'config', v_previous.config
            )
        end,
        jsonb_build_object(
            'algorithm', v_current.algorithm,
            'config', v_current.config
        ),
        p_reason
    );

    return v_current;
end;
$$;


-- ---------------------------------------------------------------------------
-- API ingest worker
-- ---------------------------------------------------------------------------

create or replace function public.lf_enqueue_api_ingest_job(
    p_request_id text,
    p_correlation_id text,
    p_http_method text,
    p_route text,
    p_query_present boolean default false,
    p_received_at timestamptz default now(),
    p_priority smallint default 100,
    p_max_attempts integer default 5,
    p_payload jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
as $$
declare
    v_job_id uuid;
begin
    insert into public.api_ingest_jobs (
        request_id,
        correlation_id,
        http_method,
        route,
        query_present,
        received_at,
        priority,
        max_attempts,
        payload
    )
    values (
        btrim(p_request_id),
        nullif(btrim(p_correlation_id), ''),
        upper(btrim(p_http_method)),
        btrim(p_route),
        coalesce(p_query_present, false),
        coalesce(p_received_at, now()),
        p_priority,
        p_max_attempts,
        coalesce(p_payload, '{}'::jsonb)
    )
    on conflict (request_id) do update
    set
        correlation_id = excluded.correlation_id,
        http_method = excluded.http_method,
        route = excluded.route,
        query_present = excluded.query_present,
        priority = excluded.priority,
        max_attempts = excluded.max_attempts,
        payload = excluded.payload,
        available_at = least(public.api_ingest_jobs.available_at, now())
    returning id into v_job_id;

    return v_job_id;
end;
$$;


create or replace function public.lf_claim_api_ingest_jobs(
    p_worker_id text,
    p_batch_size integer default 100,
    p_lock_timeout_seconds integer default 300
)
returns setof public.api_ingest_jobs
language plpgsql
as $$
begin
    if p_batch_size < 1 or p_batch_size > 1000 then
        raise exception 'batch_size must be between 1 and 1000';
    end if;

    update public.api_ingest_jobs
    set
        status = 'retry',
        locked_at = null,
        locked_by = null,
        processing_started_at = null,
        available_at = now(),
        last_error_type = coalesce(last_error_type, 'WorkerLockExpired'),
        last_error_code = coalesce(last_error_code, 'WORKER_LOCK_EXPIRED'),
        last_error_message = coalesce(
            last_error_message,
            'Worker lock expired before completion'
        )
    where
        status = 'processing'
        and locked_at < now() - make_interval(secs => p_lock_timeout_seconds);

    return query
    with selected as (
        select id
        from public.api_ingest_jobs
        where
            status in ('pending', 'retry')
            and available_at <= now()
            and attempt_count < max_attempts
        order by
            priority asc,
            available_at asc,
            received_at asc
        for update skip locked
        limit p_batch_size
    )
    update public.api_ingest_jobs jobs
    set
        status = 'processing',
        locked_at = now(),
        locked_by = btrim(p_worker_id),
        processing_started_at = now(),
        attempt_count = jobs.attempt_count + 1
    from selected
    where jobs.id = selected.id
    returning jobs.*;
end;
$$;


create or replace function public.lf_fail_api_ingest_job(
    p_job_id uuid,
    p_worker_id text,
    p_error_type text,
    p_error_code text,
    p_error_message text,
    p_retry_delay_seconds integer default 5
)
returns text
language plpgsql
as $$
declare
    v_status text;
begin
    update public.api_ingest_jobs
    set
        status = case
            when attempt_count >= max_attempts then 'failed'
            else 'retry'
        end,
        available_at = case
            when attempt_count >= max_attempts then available_at
            else now() + make_interval(
                secs => greatest(p_retry_delay_seconds, 0)
            )
        end,
        locked_at = null,
        locked_by = null,
        completed_at = case
            when attempt_count >= max_attempts then now()
            else null
        end,
        last_error_type = p_error_type,
        last_error_code = p_error_code,
        last_error_message = left(p_error_message, 2000)
    where
        id = p_job_id
        and status = 'processing'
        and locked_by = p_worker_id
    returning status into v_status;

    return v_status;
end;
$$;


-- ---------------------------------------------------------------------------
-- API history and attempts
-- ---------------------------------------------------------------------------

create or replace function public.lf_save_api_request(
    p_request jsonb,
    p_attempts jsonb default '[]'::jsonb
)
returns uuid
language plpgsql
as $$
declare
    v_api_request_id uuid;
    v_request_id text;
    v_attempt_count integer;
begin
    if jsonb_typeof(p_request) <> 'object' then
        raise exception 'p_request must be a JSON object';
    end if;

    if jsonb_typeof(coalesce(p_attempts, '[]'::jsonb)) <> 'array' then
        raise exception 'p_attempts must be a JSON array';
    end if;

    v_request_id := nullif(btrim(p_request ->> 'request_id'), '');

    if v_request_id is null then
        raise exception 'request_id is required';
    end if;

    v_attempt_count := jsonb_array_length(coalesce(p_attempts, '[]'::jsonb));

    insert into public.api_request_history (
        request_id,
        correlation_id,
        received_at,
        completed_at,
        http_method,
        route,
        query_present,
        request_size_bytes,
        response_size_bytes,
        final_status_code,
        total_duration_ms,
        selected_algorithm,
        final_backend_id,
        attempt_count,
        retry_count,
        outcome,
        error_type,
        error_code,
        error_message,
        worker_job_id,
        load_test_run_id,
        client_ip,
        client_ip_hash,
        user_agent_family,
        metadata
    )
    values (
        v_request_id,
        nullif(btrim(p_request ->> 'correlation_id'), ''),
        (p_request ->> 'received_at')::timestamptz,
        (p_request ->> 'completed_at')::timestamptz,
        upper(p_request ->> 'http_method'),
        p_request ->> 'route',
        coalesce((p_request ->> 'query_present')::boolean, false),
        nullif(p_request ->> 'request_size_bytes', '')::bigint,
        nullif(p_request ->> 'response_size_bytes', '')::bigint,
        (p_request ->> 'final_status_code')::integer,
        (p_request ->> 'total_duration_ms')::numeric,
        coalesce(nullif(p_request ->> 'selected_algorithm', ''), 'none'),
        nullif(p_request ->> 'final_backend_id', ''),
        greatest(
            coalesce(
                nullif(p_request ->> 'attempt_count', '')::integer,
                v_attempt_count
            ),
            v_attempt_count
        ),
        coalesce(
            nullif(p_request ->> 'retry_count', '')::integer,
            greatest(v_attempt_count - 1, 0)
        ),
        p_request ->> 'outcome',
        nullif(p_request ->> 'error_type', ''),
        nullif(p_request ->> 'error_code', ''),
        nullif(p_request ->> 'error_message', ''),
        nullif(p_request ->> 'worker_job_id', '')::uuid,
        nullif(p_request ->> 'load_test_run_id', '')::uuid,
        nullif(p_request ->> 'client_ip', '')::inet,
        nullif(p_request ->> 'client_ip_hash', ''),
        nullif(p_request ->> 'user_agent_family', ''),
        coalesce(p_request -> 'metadata', '{}'::jsonb)
    )
    on conflict (request_id) do update
    set
        correlation_id = excluded.correlation_id,
        completed_at = excluded.completed_at,
        http_method = excluded.http_method,
        route = excluded.route,
        query_present = excluded.query_present,
        request_size_bytes = excluded.request_size_bytes,
        response_size_bytes = excluded.response_size_bytes,
        final_status_code = excluded.final_status_code,
        total_duration_ms = excluded.total_duration_ms,
        selected_algorithm = excluded.selected_algorithm,
        final_backend_id = excluded.final_backend_id,
        attempt_count = excluded.attempt_count,
        retry_count = excluded.retry_count,
        outcome = excluded.outcome,
        error_type = excluded.error_type,
        error_code = excluded.error_code,
        error_message = excluded.error_message,
        worker_job_id = excluded.worker_job_id,
        load_test_run_id = excluded.load_test_run_id,
        client_ip = excluded.client_ip,
        client_ip_hash = excluded.client_ip_hash,
        user_agent_family = excluded.user_agent_family,
        metadata = excluded.metadata
    returning id into v_api_request_id;

    insert into public.api_request_attempts (
        api_request_id,
        request_id,
        attempt_number,
        backend_id,
        selected_algorithm,
        started_at,
        completed_at,
        duration_ms,
        upstream_status_code,
        outcome,
        retryable,
        retry_scheduled,
        error_type,
        error_code,
        error_message,
        metadata
    )
    select
        v_api_request_id,
        v_request_id,
        coalesce(
            nullif(item.value ->> 'attempt_number', '')::integer,
            item.ordinality::integer
        ),
        nullif(item.value ->> 'backend_id', ''),
        coalesce(
            nullif(item.value ->> 'selected_algorithm', ''),
            coalesce(nullif(p_request ->> 'selected_algorithm', ''), 'none')
        ),
        (item.value ->> 'started_at')::timestamptz,
        (item.value ->> 'completed_at')::timestamptz,
        (item.value ->> 'duration_ms')::numeric,
        nullif(item.value ->> 'upstream_status_code', '')::integer,
        item.value ->> 'outcome',
        coalesce((item.value ->> 'retryable')::boolean, false),
        coalesce((item.value ->> 'retry_scheduled')::boolean, false),
        nullif(item.value ->> 'error_type', ''),
        nullif(item.value ->> 'error_code', ''),
        nullif(item.value ->> 'error_message', ''),
        coalesce(item.value -> 'metadata', '{}'::jsonb)
    from jsonb_array_elements(coalesce(p_attempts, '[]'::jsonb))
        with ordinality as item(value, ordinality)
    on conflict (api_request_id, attempt_number) do update
    set
        backend_id = excluded.backend_id,
        selected_algorithm = excluded.selected_algorithm,
        started_at = excluded.started_at,
        completed_at = excluded.completed_at,
        duration_ms = excluded.duration_ms,
        upstream_status_code = excluded.upstream_status_code,
        outcome = excluded.outcome,
        retryable = excluded.retryable,
        retry_scheduled = excluded.retry_scheduled,
        error_type = excluded.error_type,
        error_code = excluded.error_code,
        error_message = excluded.error_message,
        metadata = excluded.metadata;

    return v_api_request_id;
end;
$$;


create or replace function public.lf_save_api_request_and_complete_job(
    p_job_id uuid,
    p_worker_id text,
    p_request jsonb,
    p_attempts jsonb default '[]'::jsonb
)
returns uuid
language plpgsql
as $$
declare
    v_api_request_id uuid;
    v_updated integer;
begin
    p_request := jsonb_set(
        coalesce(p_request, '{}'::jsonb),
        '{worker_job_id}',
        to_jsonb(p_job_id::text),
        true
    );

    v_api_request_id := public.lf_save_api_request(
        p_request,
        p_attempts
    );

    update public.api_ingest_jobs
    set
        status = 'completed',
        completed_at = now(),
        locked_at = null,
        locked_by = null,
        last_error_type = null,
        last_error_code = null,
        last_error_message = null
    where
        id = p_job_id
        and status = 'processing'
        and locked_by = p_worker_id;

    get diagnostics v_updated = row_count;

    if v_updated <> 1 then
        raise exception
            'Worker job % could not be completed by worker %',
            p_job_id,
            p_worker_id;
    end if;

    return v_api_request_id;
end;
$$;


-- ---------------------------------------------------------------------------
-- Health storage and status transition
-- ---------------------------------------------------------------------------

create or replace function public.lf_record_backend_health(
    p_backend_id text,
    p_success boolean,
    p_latency_ms numeric,
    p_status_code integer default null,
    p_error_type text default null,
    p_error_message text default null,
    p_healthy_threshold integer default 2,
    p_unhealthy_threshold integer default 3,
    p_metadata jsonb default '{}'::jsonb
)
returns public.backend_runtime_state
language plpgsql
as $$
declare
    v_enabled boolean;
    v_state public.backend_runtime_state;
    v_old_status text;
    v_new_status text;
    v_successes integer;
    v_failures integer;
begin
    select b.enabled
    into v_enabled
    from public.backend_services b
    join public.backend_runtime_state s
      on s.backend_id = b.id
    where
        b.id = p_backend_id
        and b.deleted_at is null
    for update of s;

    if not found then
        raise exception 'Backend not found: %', p_backend_id;
    end if;

    select *
    into v_state
    from public.backend_runtime_state
    where backend_id = p_backend_id;

    v_old_status := v_state.status;

    if p_success then
        v_successes := v_state.consecutive_successes + 1;
        v_failures := 0;
    else
        v_successes := 0;
        v_failures := v_state.consecutive_failures + 1;
    end if;

    if not v_enabled then
        v_new_status := 'disabled';
    elsif v_old_status = 'draining' then
        v_new_status := 'draining';
    elsif p_success and v_successes >= p_healthy_threshold then
        v_new_status := 'healthy';
    elsif not p_success and v_failures >= p_unhealthy_threshold then
        v_new_status := 'unhealthy';
    else
        v_new_status := v_old_status;
    end if;

    update public.backend_runtime_state
    set
        status = v_new_status,
        last_latency_ms = p_latency_ms,
        last_checked_at = now(),
        last_error = case
            when p_success then null
            else coalesce(p_error_message, p_error_type)
        end,
        consecutive_successes = v_successes,
        consecutive_failures = v_failures
    where backend_id = p_backend_id
    returning * into v_state;

    insert into public.backend_health_checks (
        backend_id,
        success,
        status_code,
        latency_ms,
        error_type,
        error_message,
        consecutive_successes,
        consecutive_failures,
        resulting_status,
        metadata
    )
    values (
        p_backend_id,
        p_success,
        p_status_code,
        p_latency_ms,
        p_error_type,
        p_error_message,
        v_successes,
        v_failures,
        v_new_status,
        coalesce(p_metadata, '{}'::jsonb)
    );

    if v_old_status is distinct from v_new_status then
        insert into public.backend_state_events (
            backend_id,
            from_status,
            to_status,
            event_type,
            reason,
            source,
            metadata
        )
        values (
            p_backend_id,
            v_old_status,
            v_new_status,
            'health_status_changed',
            case
                when p_success then 'Healthy threshold reached'
                else coalesce(p_error_message, 'Unhealthy threshold reached')
            end,
            'health_checker',
            coalesce(p_metadata, '{}'::jsonb)
        );
    end if;

    return v_state;
end;
$$;


-- ---------------------------------------------------------------------------
-- Security event storage
-- ---------------------------------------------------------------------------

create or replace function public.lf_record_security_event(
    p_event_type text,
    p_title text,
    p_client_ip inet default null,
    p_severity text default 'warning',
    p_request_id text default null,
    p_correlation_id text default null,
    p_route text default null,
    p_http_method text default null,
    p_blocked boolean default false,
    p_client_ip_hash text default null,
    p_metadata jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
as $$
declare
    v_event_id uuid;
begin
    insert into public.security_events (
        event_type,
        severity,
        title,
        client_ip,
        client_ip_hash,
        request_id,
        correlation_id,
        route,
        http_method,
        blocked,
        metadata
    )
    values (
        p_event_type,
        p_severity,
        p_title,
        p_client_ip,
        p_client_ip_hash,
        p_request_id,
        p_correlation_id,
        p_route,
        upper(p_http_method),
        p_blocked,
        coalesce(p_metadata, '{}'::jsonb)
    )
    returning id into v_event_id;

    if p_client_ip is not null then
        insert into public.security_ip_counters (
            client_ip,
            rate_limit_hits,
            auth_failures,
            suspicious_events
        )
        values (
            p_client_ip,
            case when p_event_type = 'rate_limit_exceeded' then 1 else 0 end,
            case when p_event_type = 'auth_failure' then 1 else 0 end,
            case
                when p_event_type in (
                    'suspicious_request',
                    'sql_injection_detected',
                    'suspicious_user_agent'
                )
                then 1
                else 0
            end
        )
        on conflict (client_ip) do update
        set
            rate_limit_hits =
                public.security_ip_counters.rate_limit_hits
                + excluded.rate_limit_hits,
            auth_failures =
                public.security_ip_counters.auth_failures
                + excluded.auth_failures,
            suspicious_events =
                public.security_ip_counters.suspicious_events
                + excluded.suspicious_events,
            last_seen_at = now();
    end if;

    return v_event_id;
end;
$$;


-- ---------------------------------------------------------------------------
-- Load-test storage
-- ---------------------------------------------------------------------------

create or replace function public.lf_start_load_test(
    p_external_id text,
    p_target_path text,
    p_duration_seconds integer,
    p_concurrency integer,
    p_algorithm text default null,
    p_name text default null,
    p_created_by text default null,
    p_parameters jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
as $$
declare
    v_id uuid;
begin
    insert into public.load_test_runs (
        external_id,
        name,
        target_path,
        status,
        duration_seconds,
        concurrency,
        selected_algorithm,
        started_at,
        progress,
        parameters,
        created_by
    )
    values (
        p_external_id,
        p_name,
        p_target_path,
        'running',
        p_duration_seconds,
        p_concurrency,
        p_algorithm,
        now(),
        0,
        coalesce(p_parameters, '{}'::jsonb),
        p_created_by
    )
    on conflict (external_id) do update
    set
        status = 'running',
        started_at = now(),
        completed_at = null,
        progress = 0,
        throughput_rps = 0,
        average_latency_ms = 0,
        p50_latency_ms = 0,
        p95_latency_ms = 0,
        p99_latency_ms = 0,
        error_rate = 0,
        success_count = 0,
        error_count = 0,
        parameters = excluded.parameters
    returning id into v_id;

    return v_id;
end;
$$;


create or replace function public.lf_record_load_test_sample(
    p_load_test_run_id uuid,
    p_progress integer,
    p_throughput_rps numeric,
    p_average_latency_ms numeric,
    p_p50_latency_ms numeric,
    p_p95_latency_ms numeric,
    p_p99_latency_ms numeric,
    p_success_count bigint,
    p_error_count bigint,
    p_error_rate numeric,
    p_metadata jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
as $$
declare
    v_sample_id bigint;
begin
    insert into public.load_test_samples (
        load_test_run_id,
        progress,
        throughput_rps,
        average_latency_ms,
        p50_latency_ms,
        p95_latency_ms,
        p99_latency_ms,
        success_count,
        error_count,
        error_rate,
        metadata
    )
    values (
        p_load_test_run_id,
        p_progress,
        p_throughput_rps,
        p_average_latency_ms,
        p_p50_latency_ms,
        p_p95_latency_ms,
        p_p99_latency_ms,
        p_success_count,
        p_error_count,
        p_error_rate,
        coalesce(p_metadata, '{}'::jsonb)
    )
    returning id into v_sample_id;

    update public.load_test_runs
    set
        progress = p_progress,
        throughput_rps = p_throughput_rps,
        average_latency_ms = p_average_latency_ms,
        p50_latency_ms = p_p50_latency_ms,
        p95_latency_ms = p_p95_latency_ms,
        p99_latency_ms = p_p99_latency_ms,
        success_count = p_success_count,
        error_count = p_error_count,
        error_rate = p_error_rate
    where id = p_load_test_run_id;

    return v_sample_id;
end;
$$;


create or replace function public.lf_finish_load_test(
    p_load_test_run_id uuid,
    p_status text,
    p_throughput_rps numeric,
    p_average_latency_ms numeric,
    p_p50_latency_ms numeric,
    p_p95_latency_ms numeric,
    p_p99_latency_ms numeric,
    p_success_count bigint,
    p_error_count bigint,
    p_error_rate numeric,
    p_result_metadata jsonb default '{}'::jsonb
)
returns public.load_test_runs
language plpgsql
as $$
declare
    v_run public.load_test_runs;
begin
    update public.load_test_runs
    set
        status = p_status,
        completed_at = now(),
        progress = case
            when p_status = 'completed' then 100
            else progress
        end,
        throughput_rps = p_throughput_rps,
        average_latency_ms = p_average_latency_ms,
        p50_latency_ms = p_p50_latency_ms,
        p95_latency_ms = p_p95_latency_ms,
        p99_latency_ms = p_p99_latency_ms,
        success_count = p_success_count,
        error_count = p_error_count,
        error_rate = p_error_rate,
        result_metadata = coalesce(p_result_metadata, '{}'::jsonb)
    where id = p_load_test_run_id
    returning * into v_run;

    if not found then
        raise exception 'Load-test run not found: %', p_load_test_run_id;
    end if;

    return v_run;
end;
$$;


-- ---------------------------------------------------------------------------
-- System logs, audit, acknowledgements, and pool samples
-- ---------------------------------------------------------------------------

create or replace function public.lf_write_system_log(
    p_level text,
    p_event_name text,
    p_component text,
    p_message text,
    p_request_id text default null,
    p_correlation_id text default null,
    p_backend_id text default null,
    p_http_method text default null,
    p_route text default null,
    p_status_code integer default null,
    p_duration_ms numeric default null,
    p_error_type text default null,
    p_error_code text default null,
    p_metadata jsonb default '{}'::jsonb,
    p_occurred_at timestamptz default now()
)
returns uuid
language plpgsql
as $$
declare
    v_id uuid;
begin
    insert into public.system_logs (
        occurred_at,
        level,
        event_name,
        component,
        message,
        request_id,
        correlation_id,
        backend_id,
        http_method,
        route,
        status_code,
        duration_ms,
        error_type,
        error_code,
        metadata
    )
    values (
        coalesce(p_occurred_at, now()),
        p_level,
        p_event_name,
        p_component,
        p_message,
        p_request_id,
        p_correlation_id,
        p_backend_id,
        upper(p_http_method),
        p_route,
        p_status_code,
        p_duration_ms,
        p_error_type,
        p_error_code,
        coalesce(p_metadata, '{}'::jsonb)
    )
    returning id into v_id;

    return v_id;
end;
$$;


create or replace function public.lf_write_audit_event(
    p_action text,
    p_object_type text,
    p_object_id text default null,
    p_actor_id text default null,
    p_actor_type text default 'admin_api_key',
    p_previous_state jsonb default null,
    p_new_state jsonb default null,
    p_reason text default null,
    p_request_id text default null,
    p_correlation_id text default null,
    p_client_ip inet default null,
    p_metadata jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
as $$
declare
    v_id uuid;
begin
    insert into public.audit_events (
        actor_id,
        actor_type,
        action,
        object_type,
        object_id,
        previous_state,
        new_state,
        reason,
        request_id,
        correlation_id,
        client_ip,
        metadata
    )
    values (
        p_actor_id,
        p_actor_type,
        p_action,
        p_object_type,
        p_object_id,
        p_previous_state,
        p_new_state,
        p_reason,
        p_request_id,
        p_correlation_id,
        p_client_ip,
        coalesce(p_metadata, '{}'::jsonb)
    )
    returning id into v_id;

    return v_id;
end;
$$;


create or replace function public.lf_acknowledge_alert(
    p_alert_key text,
    p_actor_id text default 'default-admin',
    p_note text default null
)
returns boolean
language plpgsql
as $$
begin
    insert into public.alert_acknowledgements (
        alert_key,
        actor_id,
        note
    )
    values (
        p_alert_key,
        p_actor_id,
        p_note
    )
    on conflict (alert_key, actor_id) do update
    set
        acknowledged_at = now(),
        note = excluded.note;

    return true;
end;
$$;


create or replace function public.lf_record_db_pool_sample(
    p_instance_id text,
    p_configured_pool_size integer,
    p_checked_in_connections integer,
    p_checked_out_connections integer,
    p_overflow_connections integer,
    p_acquisition_wait_ms numeric default null,
    p_timeout_count bigint default 0,
    p_connection_error_count bigint default 0,
    p_metadata jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
as $$
declare
    v_id bigint;
begin
    insert into public.db_pool_samples (
        instance_id,
        configured_pool_size,
        checked_in_connections,
        checked_out_connections,
        overflow_connections,
        acquisition_wait_ms,
        timeout_count,
        connection_error_count,
        metadata
    )
    values (
        p_instance_id,
        p_configured_pool_size,
        p_checked_in_connections,
        p_checked_out_connections,
        p_overflow_connections,
        p_acquisition_wait_ms,
        p_timeout_count,
        p_connection_error_count,
        coalesce(p_metadata, '{}'::jsonb)
    )
    returning id into v_id;

    return v_id;
end;
$$;

commit;

-- =====================================================================
-- FILE: 13_dashboard_views.sql
-- =====================================================================

-- Read-only views matching the current dashboard pages.

begin;

create or replace view public.lf_v_backend_status as
select
    b.id,
    b.name,
    b.url,
    b.weight,
    b.enabled,
    s.status,
    s.active_requests,
    s.total_requests,
    s.total_errors,
    s.last_latency_ms,
    s.last_checked_at,
    s.last_error,
    s.consecutive_successes,
    s.consecutive_failures,
    case
        when b.enabled
         and s.status in ('healthy', 'unknown')
        then true
        else false
    end as eligible,
    case
        when s.total_requests = 0 then 0::numeric
        else round(
            s.total_errors::numeric / s.total_requests::numeric * 100,
            2
        )
    end as error_rate,
    b.created_at,
    b.updated_at
from public.backend_services b
join public.backend_runtime_state s
  on s.backend_id = b.id
where b.deleted_at is null;


create or replace view public.lf_v_recent_request_logs as
select
    r.request_id,
    r.completed_at as timestamp,
    r.http_method as method,
    r.route as path,
    r.final_backend_id as backend_id,
    r.final_status_code as status_code,
    r.total_duration_ms as duration_ms,
    r.error_message as error,
    r.retry_count
from public.api_request_history r;


create or replace view public.lf_v_request_overview_24h as
with scoped as (
    select *
    from public.api_request_history
    where received_at >= now() - interval '24 hours'
),
duration_stats as (
    select
        count(*)::bigint as total_requests,
        coalesce(avg(total_duration_ms), 0)::numeric as average_latency_ms,
        coalesce(
            percentile_cont(0.95) within group (
                order by total_duration_ms
            ),
            0
        )::numeric as p95_latency_ms,
        coalesce(
            percentile_cont(0.99) within group (
                order by total_duration_ms
            ),
            0
        )::numeric as p99_latency_ms,
        count(*) filter (
            where final_status_code >= 500
               or error_type is not null
        )::bigint as error_count,
        min(received_at) as first_received_at,
        max(completed_at) as last_completed_at
    from scoped
)
select
    total_requests,
    round(
        total_requests::numeric
        / greatest(
            extract(
                epoch from (
                    coalesce(last_completed_at, now())
                    - coalesce(first_received_at, now())
                )
            ),
            1
        ),
        2
    ) as requests_per_second,
    round(average_latency_ms, 2) as average_latency_ms,
    round(p95_latency_ms, 2) as p95_latency_ms,
    round(p99_latency_ms, 2) as p99_latency_ms,
    round(
        case
            when total_requests = 0 then 0
            else error_count::numeric / total_requests::numeric * 100
        end,
        2
    ) as error_rate
from duration_stats;


create or replace view public.lf_v_endpoint_analytics_24h as
select
    route as path,
    count(*)::bigint as requests,
    round(avg(total_duration_ms), 2) as average_latency_ms,
    round(
        percentile_cont(0.95) within group (
            order by total_duration_ms
        )::numeric,
        2
    ) as p95_latency_ms,
    round(
        percentile_cont(0.99) within group (
            order by total_duration_ms
        )::numeric,
        2
    ) as p99_latency_ms,
    round(
        count(*) filter (
            where final_status_code >= 500
               or error_type is not null
        )::numeric
        / greatest(count(*)::numeric, 1)
        * 100,
        2
    ) as error_rate
from public.api_request_history
where received_at >= now() - interval '24 hours'
group by route;


create or replace view public.lf_v_backend_distribution_24h as
select
    coalesce(final_backend_id, 'none') as backend_id,
    count(*)::bigint as request_count,
    round(
        count(*)::numeric
        / greatest(
            sum(count(*)) over (),
            1
        )::numeric
        * 100,
        2
    ) as traffic_share_percent
from public.api_request_history
where received_at >= now() - interval '24 hours'
group by coalesce(final_backend_id, 'none');


create or replace view public.lf_v_request_timeseries_15s as
select
    to_timestamp(
        floor(extract(epoch from received_at) / 15) * 15
    ) as bucket_start,
    count(*)::bigint as requests,
    count(*) filter (
        where final_status_code >= 500
           or error_type is not null
    )::bigint as errors,
    round(avg(total_duration_ms), 2) as average_latency_ms
from public.api_request_history
group by 1;


create or replace view public.lf_v_security_summary_24h as
select
    count(distinct client_ip) filter (
        where blocked = true
    )::bigint as blocked_ips_count,
    count(*) filter (
        where event_type = 'rate_limit_exceeded'
    )::bigint as rate_limit_hits,
    count(*) filter (
        where event_type = 'auth_failure'
    )::bigint as auth_failures,
    count(*) filter (
        where event_type in (
            'suspicious_request',
            'sql_injection_detected',
            'suspicious_user_agent'
        )
    )::bigint as suspicious_events
from public.security_events
where occurred_at >= now() - interval '24 hours';


create or replace view public.lf_v_load_test_history as
select
    id,
    external_id,
    name,
    target_path,
    status,
    duration_seconds,
    concurrency,
    selected_algorithm,
    started_at,
    completed_at,
    progress,
    throughput_rps,
    average_latency_ms,
    p50_latency_ms,
    p95_latency_ms,
    p99_latency_ms,
    error_rate,
    success_count,
    error_count,
    total_requests,
    created_at
from public.load_test_runs;


create or replace view public.lf_v_latest_db_pool_samples as
select distinct on (instance_id)
    instance_id,
    sampled_at,
    configured_pool_size,
    checked_in_connections,
    checked_out_connections,
    overflow_connections,
    acquisition_wait_ms,
    timeout_count,
    connection_error_count,
    metadata
from public.db_pool_samples
order by instance_id, sampled_at desc;

commit;

-- =====================================================================
-- FILE: 14_alert_and_retention_functions.sql
-- =====================================================================

-- Active alerts and configurable cleanup functions.

begin;

create or replace function public.lf_get_active_alerts(
    p_actor_id text default 'default-admin',
    p_limit integer default 100
)
returns table (
    alert_key text,
    title text,
    source text,
    level text,
    occurred_at timestamptz,
    metadata jsonb
)
language sql
stable
as $$
with candidate_alerts as (
    select
        'backend-status-' || b.id || '-' || s.status as alert_key,
        case
            when s.status = 'unhealthy'
                then 'Health check failed for ' || b.name
            when s.status = 'draining'
                then 'Traffic draining enabled for ' || b.name
            when s.status = 'disabled'
                then 'Backend ' || b.name || ' has been disabled'
            else 'Backend state changed for ' || b.name
        end as title,
        'Backend: ' || b.id as source,
        case
            when s.status = 'unhealthy' then 'Critical'
            else 'Warning'
        end as level,
        coalesce(s.last_checked_at, s.updated_at) as occurred_at,
        jsonb_build_object(
            'backend_id', b.id,
            'status', s.status,
            'last_error', s.last_error
        ) as metadata
    from public.backend_services b
    join public.backend_runtime_state s
      on s.backend_id = b.id
    where b.deleted_at is null
      and s.status in ('unhealthy', 'draining', 'disabled')

    union all

    select
        'request-error-' || r.request_id,
        case
            when r.error_message is not null
                then 'Proxy error: ' || r.error_message
            else 'HTTP ' || r.final_status_code::text
                 || ' on ' || r.http_method || ' ' || r.route
        end,
        'Request ID: ' || r.request_id,
        case
            when r.final_status_code >= 500
              or r.error_type is not null
                then 'Critical'
            else 'Warning'
        end,
        r.completed_at,
        jsonb_build_object(
            'request_id', r.request_id,
            'status_code', r.final_status_code,
            'backend_id', r.final_backend_id,
            'error_type', r.error_type
        )
    from public.api_request_history r
    where r.completed_at >= now() - interval '24 hours'
      and (
          r.final_status_code >= 400
          or r.error_type is not null
      )

    union all

    select
        'security-' || e.id::text,
        e.title,
        coalesce(e.client_ip::text, 'Security monitor'),
        case
            when e.severity in ('error', 'critical')
                then 'Critical'
            else 'Warning'
        end,
        e.occurred_at,
        jsonb_build_object(
            'event_type', e.event_type,
            'client_ip', e.client_ip,
            'request_id', e.request_id
        )
    from public.security_events e
    where e.occurred_at >= now() - interval '24 hours'
      and e.severity in ('warning', 'error', 'critical')
)
select
    c.alert_key,
    c.title,
    c.source,
    c.level,
    c.occurred_at,
    c.metadata
from candidate_alerts c
left join public.alert_acknowledgements a
  on a.alert_key = c.alert_key
 and a.actor_id = p_actor_id
where a.alert_key is null
order by c.occurred_at desc
limit greatest(least(p_limit, 500), 1);
$$;


create or replace function public.lf_cleanup_expired_data(
    p_request_retention_days integer default 30,
    p_health_retention_days integer default 14,
    p_system_log_retention_days integer default 30,
    p_security_retention_days integer default 90,
    p_worker_retention_days integer default 7,
    p_pool_sample_retention_days integer default 14
)
returns jsonb
language plpgsql
as $$
declare
    v_requests bigint;
    v_health bigint;
    v_logs bigint;
    v_security bigint;
    v_workers bigint;
    v_pool bigint;
begin
    delete from public.api_request_history
    where received_at
        < now() - make_interval(days => p_request_retention_days);
    get diagnostics v_requests = row_count;

    delete from public.backend_health_checks
    where checked_at
        < now() - make_interval(days => p_health_retention_days);
    get diagnostics v_health = row_count;

    delete from public.system_logs
    where occurred_at
        < now() - make_interval(days => p_system_log_retention_days);
    get diagnostics v_logs = row_count;

    delete from public.security_events
    where occurred_at
        < now() - make_interval(days => p_security_retention_days);
    get diagnostics v_security = row_count;

    delete from public.api_ingest_jobs
    where status in ('completed', 'failed', 'discarded')
      and coalesce(completed_at, updated_at)
        < now() - make_interval(days => p_worker_retention_days);
    get diagnostics v_workers = row_count;

    delete from public.db_pool_samples
    where sampled_at
        < now() - make_interval(days => p_pool_sample_retention_days);
    get diagnostics v_pool = row_count;

    return jsonb_build_object(
        'api_requests_deleted', v_requests,
        'health_checks_deleted', v_health,
        'system_logs_deleted', v_logs,
        'security_events_deleted', v_security,
        'worker_jobs_deleted', v_workers,
        'pool_samples_deleted', v_pool
    );
end;
$$;

commit;

-- =====================================================================
-- FILE: 15_rls_and_permissions.sql
-- =====================================================================

-- Backend-only access model.
--
-- anon/authenticated are intentionally blocked.
-- Direct PostgreSQL connections using the database owner continue to work.
-- Supabase service_role may be used only from trusted backend infrastructure.

begin;

alter table public.backend_services enable row level security;
alter table public.backend_runtime_state enable row level security;
alter table public.backend_state_events enable row level security;
alter table public.routing_configuration enable row level security;
alter table public.routing_configuration_history enable row level security;
alter table public.platform_settings enable row level security;
alter table public.load_test_runs enable row level security;
alter table public.load_test_samples enable row level security;
alter table public.load_test_backend_results enable row level security;
alter table public.api_ingest_jobs enable row level security;
alter table public.api_request_history enable row level security;
alter table public.api_request_attempts enable row level security;
alter table public.backend_health_checks enable row level security;
alter table public.security_events enable row level security;
alter table public.security_ip_counters enable row level security;
alter table public.system_logs enable row level security;
alter table public.audit_events enable row level security;
alter table public.alert_acknowledgements enable row level security;
alter table public.db_pool_samples enable row level security;

revoke all on table public.backend_services
    from anon, authenticated;
revoke all on table public.backend_runtime_state
    from anon, authenticated;
revoke all on table public.backend_state_events
    from anon, authenticated;
revoke all on table public.routing_configuration
    from anon, authenticated;
revoke all on table public.routing_configuration_history
    from anon, authenticated;
revoke all on table public.platform_settings
    from anon, authenticated;
revoke all on table public.load_test_runs
    from anon, authenticated;
revoke all on table public.load_test_samples
    from anon, authenticated;
revoke all on table public.load_test_backend_results
    from anon, authenticated;
revoke all on table public.api_ingest_jobs
    from anon, authenticated;
revoke all on table public.api_request_history
    from anon, authenticated;
revoke all on table public.api_request_attempts
    from anon, authenticated;
revoke all on table public.backend_health_checks
    from anon, authenticated;
revoke all on table public.security_events
    from anon, authenticated;
revoke all on table public.security_ip_counters
    from anon, authenticated;
revoke all on table public.system_logs
    from anon, authenticated;
revoke all on table public.audit_events
    from anon, authenticated;
revoke all on table public.alert_acknowledgements
    from anon, authenticated;
revoke all on table public.db_pool_samples
    from anon, authenticated;

revoke all on table public.lf_v_backend_status
    from anon, authenticated;
revoke all on table public.lf_v_recent_request_logs
    from anon, authenticated;
revoke all on table public.lf_v_request_overview_24h
    from anon, authenticated;
revoke all on table public.lf_v_endpoint_analytics_24h
    from anon, authenticated;
revoke all on table public.lf_v_backend_distribution_24h
    from anon, authenticated;
revoke all on table public.lf_v_request_timeseries_15s
    from anon, authenticated;
revoke all on table public.lf_v_security_summary_24h
    from anon, authenticated;
revoke all on table public.lf_v_load_test_history
    from anon, authenticated;
revoke all on table public.lf_v_latest_db_pool_samples
    from anon, authenticated;

-- PostgreSQL grants EXECUTE on new functions to PUBLIC by default.
-- Revoke only LoadFlow functions, identified by the lf_ prefix.
do $$
declare
    item record;
begin
    for item in
        select
            p.oid::regprocedure as function_signature
        from pg_proc p
        join pg_namespace n
          on n.oid = p.pronamespace
        where n.nspname = 'public'
          and p.proname like 'lf\_%' escape '\'
    loop
        execute format(
            'revoke all on function %s from public, anon, authenticated',
            item.function_signature
        );
    end loop;
end;
$$;

-- Optional trusted-server access through the Supabase service role.
grant select, insert, update, delete
    on public.backend_services,
       public.backend_runtime_state,
       public.backend_state_events,
       public.routing_configuration,
       public.routing_configuration_history,
       public.platform_settings,
       public.load_test_runs,
       public.load_test_samples,
       public.load_test_backend_results,
       public.api_ingest_jobs,
       public.api_request_history,
       public.api_request_attempts,
       public.backend_health_checks,
       public.security_events,
       public.security_ip_counters,
       public.system_logs,
       public.audit_events,
       public.alert_acknowledgements,
       public.db_pool_samples
    to service_role;

grant usage, select
    on all sequences in schema public
    to service_role;

grant select
    on public.lf_v_backend_status,
       public.lf_v_recent_request_logs,
       public.lf_v_request_overview_24h,
       public.lf_v_endpoint_analytics_24h,
       public.lf_v_backend_distribution_24h,
       public.lf_v_request_timeseries_15s,
       public.lf_v_security_summary_24h,
       public.lf_v_load_test_history,
       public.lf_v_latest_db_pool_samples
    to service_role;

do $$
declare
    item record;
begin
    for item in
        select
            p.oid::regprocedure as function_signature
        from pg_proc p
        join pg_namespace n
          on n.oid = p.pronamespace
        where n.nspname = 'public'
          and p.proname like 'lf\_%' escape '\'
    loop
        execute format(
            'grant execute on function %s to service_role',
            item.function_signature
        );
    end loop;
end;
$$;

commit;

-- =====================================================================
-- FILE: 16_seed_defaults.sql
-- =====================================================================

-- Safe defaults only. No backend URLs are seeded here.

begin;

insert into public.routing_configuration (
    singleton_id,
    algorithm,
    config,
    updated_by
)
values (
    1,
    'round_robin',
    '{}'::jsonb,
    'migration'
)
on conflict (singleton_id) do nothing;


insert into public.platform_settings (
    singleton_id,
    request_timeout_seconds,
    connect_timeout_seconds,
    health_check_enabled,
    health_check_interval_seconds,
    healthy_threshold,
    unhealthy_threshold,
    max_request_body_bytes,
    rate_limit_requests,
    rate_limit_window_seconds,
    expose_selected_backend_header,
    updated_by
)
values (
    1,
    15,
    3,
    true,
    5,
    2,
    3,
    10485760,
    300,
    60,
    false,
    'migration'
)
on conflict (singleton_id) do nothing;

commit;
